In [1]:
# load basic modules
import pandas as pd

In [2]:
# iforest model aggregated data
wt_iforest_dfCTaggr_filepath = "/lustre/bio_running/C_to_U_editing_minimap2_spliced/src_jupyter_notebooks_multi_thr//WT.df_CT_predicted_aggregated_iforest_apobec1_pvalues.tsv"
ko_iforest_dfCTaggr_filepath = "/lustre/bio_running/C_to_U_editing_minimap2_spliced/src_jupyter_notebooks_multi_thr//KO.df_CT_predicted_aggregated_iforest_apobec1_pvalues.tsv"
# cnn model aggregated data
wt_cnn_dfCTaggr_filepath = "/lustre/bio_running/C_to_U_editing_minimap2_spliced/src_jupyter_notebooks_multi_thr//WT.df_CT_predicted_aggregated_CNN_apobec1_pvalues.tsv"
ko_cnn_dfCTaggr_filepath = "/lustre/bio_running/C_to_U_editing_minimap2_spliced/src_jupyter_notebooks_multi_thr//KO.df_CT_predicted_aggregated_CNN_apobec1_pvalues.tsv"

### WT

In [3]:
wt_iforest_dfCTaggr = pd.read_csv(wt_iforest_dfCTaggr_filepath, index_col=0)
wt_iforest_dfCTaggr

,region,position,strand,T_native,T_corrected,depth_stranded,Tfreq_native,Tfreq_corrected,5mer,y_hat,p_value
0,chr1,4846611,-,2,0,100,0.020000,0.0,GTCTG,0,1.0
1,chr1,4846619,-,1,0,101,0.009901,0.0,AGCTT,0,1.0
2,chr1,4846635,-,5,0,77,0.064935,0.0,TTCTT,0,1.0
3,chr1,4846643,-,3,0,103,0.029126,0.0,CACAT,0,1.0
4,chr1,4846645,-,3,0,103,0.029126,0.0,TGCAC,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
389965,chrY,90804626,+,2,0,66,0.030303,0.0,AGCGG,0,1.0
389966,chrY,90804632,+,1,0,67,0.014925,0.0,CGCCG,0,1.0
389967,chrY,90804649,+,1,0,58,0.017241,0.0,CTCTG,0,1.0
389968,chrY,90804680,+,2,0,60,0.033333,0.0,CTCCA,0,1.0
389969,chrY,90804681,+,1,0,56,0.017857,0.0,TCCAC,0,1.0

In [4]:
wt_cnn_dfCTaggr = pd.read_csv(wt_cnn_dfCTaggr_filepath)
wt_cnn_dfCTaggr

,Unnamed: 0,region,position,strand,T_native,T_corrected,depth_stranded,Tfreq_native,Tfreq_corrected,5mer,y_hat,p_value
0,0,chr1,4846611,-,1,0,100,0.010000,0.000000,GTCTG,0,1.0
1,1,chr1,4846619,-,1,0,101,0.009901,0.000000,AGCTT,0,1.0
2,2,chr1,4846635,-,4,3,77,0.051948,0.038961,TTCTT,0,1.0
3,3,chr1,4846643,-,3,0,103,0.029126,0.000000,CACAT,0,1.0
4,4,chr1,4846645,-,3,0,103,0.029126,0.000000,TGCAC,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
331757,337784,chrY,90804626,+,2,0,66,0.030303,0.000000,AGCGG,0,1.0
331758,337785,chrY,90804632,+,1,0,67,0.014925,0.000000,CGCCG,0,1.0
331759,337786,chrY,90804649,+,1,0,58,0.017241,0.000000,CTCTG,0,1.0
331760,337787,chrY,90804680,+,2,0,60,0.033333,0.000000,CTCCA,0,1.0
331761,337788,chrY,90804681,+,1,0,56,0.017857,0.000000,TCCAC,0,1.0

In [5]:
# create ensemble predictions for Wt
wt_ensemble = pd.merge(wt_iforest_dfCTaggr, wt_cnn_dfCTaggr, how="inner", on=["region", "position", "strand"])
wt_ensemble

,region,position,strand,T_native_x,T_corrected_x,depth_stranded_x,Tfreq_native_x,Tfreq_corrected_x,5mer_x,y_hat_x,p_value_x,Unnamed: 0,T_native_y,T_corrected_y,depth_stranded_y,Tfreq_native_y,Tfreq_corrected_y,5mer_y,y_hat_y,p_value_y
0,chr1,4846611,-,2,0,100,0.020000,0.0,GTCTG,0,1.0,0,1,0,100,0.010000,0.000000,GTCTG,0,1.0
1,chr1,4846619,-,1,0,101,0.009901,0.0,AGCTT,0,1.0,1,1,0,101,0.009901,0.000000,AGCTT,0,1.0
2,chr1,4846635,-,5,0,77,0.064935,0.0,TTCTT,0,1.0,2,4,3,77,0.051948,0.038961,TTCTT,0,1.0
3,chr1,4846643,-,3,0,103,0.029126,0.0,CACAT,0,1.0,3,3,0,103,0.029126,0.000000,CACAT,0,1.0
4,chr1,4846645,-,3,0,103,0.029126,0.0,TGCAC,0,1.0,4,3,0,103,0.029126,0.000000,TGCAC,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331757,chrY,90804626,+,2,0,66,0.030303,0.0,AGCGG,0,1.0,337784,2,0,66,0.030303,0.000000,AGCGG,0,1.0
331758,chrY,90804632,+,1,0,67,0.014925,0.0,CGCCG,0,1.0,337785,1,0,67,0.014925,0.000000,CGCCG,0,1.0
331759,chrY,90804649,+,1,0,58,0.017241,0.0,CTCTG,0,1.0,337786,1,0,58,0.017241,0.000000,CTCTG,0,1.0
331760,chrY,90804680,+,2,0,60,0.033333,0.0,CTCCA,0,1.0,337787,2,0,60,0.033333,0.000000,CTCCA,0,1.0
331761,chrY,90804681,+,1,0,56,0.017857,0.0,TCCAC,0,1.0,337788,1,0,56,0.017857,0.000000,TCCAC,0,1.0

In [6]:
# create ensemble predictions for Wt after correction
wt_ensemble_corrected = pd.merge(wt_iforest_dfCTaggr.query("y_hat == 1"), 
                                 wt_cnn_dfCTaggr.query("y_hat == 1"), 
                                 how="inner", on=["region", "position", "strand"])
wt_ensemble_corrected

,region,position,strand,T_native_x,T_corrected_x,depth_stranded_x,Tfreq_native_x,Tfreq_corrected_x,5mer_x,y_hat_x,p_value_x,Unnamed: 0,T_native_y,T_corrected_y,depth_stranded_y,Tfreq_native_y,Tfreq_corrected_y,5mer_y,y_hat_y,p_value_y
0,chr1,4855906,-,58,27,61,0.950820,0.442623,CGCGG,1,1.000000,100,45,23,61,0.737705,0.377049,CGCGG,1,1.000000
1,chr1,4915375,+,3,2,51,0.058824,0.039216,GACTA,1,0.014747,110,3,2,51,0.058824,0.039216,GACTA,1,0.014747
2,chr1,4915694,+,7,4,51,0.137255,0.078431,TACTA,1,0.000521,132,7,2,51,0.137255,0.039216,TACTA,1,0.000521
3,chr1,4916336,+,20,4,67,0.298507,0.059701,GCCGA,1,0.000316,187,20,18,67,0.298507,0.268657,GCCGA,1,0.000316
4,chr1,4916406,+,3,3,67,0.044776,0.044776,GACTT,1,0.000099,197,3,3,67,0.044776,0.044776,GACTT,1,0.000099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,chrX,165992108,-,831,263,3579,0.232188,0.073484,CTCGC,1,1.000000,337612,722,140,3579,0.201732,0.039117,CTCGC,1,1.000000
4246,chrX,165992121,-,1144,195,3454,0.331210,0.056456,CTCGT,1,1.000000,337617,1120,388,3454,0.324262,0.112334,CTCGT,1,1.000000
4247,chrY,90795933,+,18,4,61,0.295082,0.065574,GGCTG,1,1.000000,337694,16,1,61,0.262295,0.016393,GGCTG,1,1.000000
4248,chrY,90797004,+,7,3,59,0.118644,0.050847,GCCGA,1,1.000000,337719,5,2,59,0.084746,0.033898,GCCGA,1,1.000000
4249,chrY,90804618,+,4,2,65,0.061538,0.030769,CACGT,1,1.000000,337783,3,2,65,0.046154,0.030769,CACGT,1,1.000000

### KO

In [7]:
ko_iforest_dfCTaggr = pd.read_csv(ko_iforest_dfCTaggr_filepath, index_col=0)
ko_iforest_dfCTaggr

,region,position,strand,T_native,T_corrected,depth_stranded,Tfreq_native,Tfreq_corrected,5mer,y_hat,p_value
0,chr1,4846611,-,2,0,113,0.017699,0.000,GTCTG,0,1.0
1,chr1,4846619,-,2,0,121,0.016529,0.000,AGCTT,0,1.0
2,chr1,4846635,-,7,0,98,0.071429,0.000,TTCTT,0,1.0
3,chr1,4846643,-,2,1,125,0.016000,0.008,CACAT,0,1.0
4,chr1,4846645,-,4,1,125,0.032000,0.008,TGCAC,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
527697,chrY,90833612,+,3,0,54,0.055556,0.000,CGCCA,0,1.0
527698,chrY,90833626,+,3,0,56,0.053571,0.000,GACTG,0,1.0
527699,chrY,90833629,+,6,0,55,0.109091,0.000,TGCGT,0,1.0
527700,chrY,90833633,+,2,0,56,0.035714,0.000,TACAG,0,1.0
527701,chrY,90833648,+,1,0,55,0.018182,0.000,CTCAA,0,1.0

In [8]:
ko_cnn_dfCTaggr = pd.read_csv(ko_cnn_dfCTaggr_filepath, index_col=0)
ko_cnn_dfCTaggr

,region,position,strand,T_native,T_corrected,depth_stranded,Tfreq_native,Tfreq_corrected,5mer,y_hat,p_value
0,chr1,4846619,-,2,0,121,0.016529,0.000000,AGCTT,0,1.0
1,chr1,4846635,-,7,3,98,0.071429,0.030612,TTCTT,0,1.0
2,chr1,4846643,-,1,0,125,0.008000,0.000000,CACAT,0,1.0
3,chr1,4846645,-,4,0,125,0.032000,0.000000,TGCAC,0,1.0
4,chr1,4846648,-,2,0,126,0.015873,0.000000,GGCTG,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
465902,chrY,90833612,+,3,0,54,0.055556,0.000000,CGCCA,0,1.0
465903,chrY,90833626,+,3,0,56,0.053571,0.000000,GACTG,0,1.0
465904,chrY,90833629,+,5,1,55,0.090909,0.018182,TGCGT,1,1.0
465905,chrY,90833633,+,2,0,56,0.035714,0.000000,TACAG,0,1.0
465906,chrY,90833648,+,1,0,55,0.018182,0.000000,CTCAA,0,1.0

In [9]:
# create ensemble predictions Ko
ko_ensemble = pd.merge(ko_iforest_dfCTaggr, ko_cnn_dfCTaggr, how="inner", on=["region", "position", "strand"])
ko_ensemble

,region,position,strand,T_native_x,T_corrected_x,depth_stranded_x,Tfreq_native_x,Tfreq_corrected_x,5mer_x,y_hat_x,p_value_x,T_native_y,T_corrected_y,depth_stranded_y,Tfreq_native_y,Tfreq_corrected_y,5mer_y,y_hat_y,p_value_y
0,chr1,4846619,-,2,0,121,0.016529,0.000,AGCTT,0,1.0,2,0,121,0.016529,0.000000,AGCTT,0,1.0
1,chr1,4846635,-,7,0,98,0.071429,0.000,TTCTT,0,1.0,7,3,98,0.071429,0.030612,TTCTT,0,1.0
2,chr1,4846643,-,2,1,125,0.016000,0.008,CACAT,0,1.0,1,0,125,0.008000,0.000000,CACAT,0,1.0
3,chr1,4846645,-,4,1,125,0.032000,0.008,TGCAC,0,1.0,4,0,125,0.032000,0.000000,TGCAC,0,1.0
4,chr1,4846648,-,2,0,126,0.015873,0.000,GGCTG,0,1.0,2,0,126,0.015873,0.000000,GGCTG,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458316,chrY,90833612,+,3,0,54,0.055556,0.000,CGCCA,0,1.0,3,0,54,0.055556,0.000000,CGCCA,0,1.0
458317,chrY,90833626,+,3,0,56,0.053571,0.000,GACTG,0,1.0,3,0,56,0.053571,0.000000,GACTG,0,1.0
458318,chrY,90833629,+,6,0,55,0.109091,0.000,TGCGT,0,1.0,5,1,55,0.090909,0.018182,TGCGT,1,1.0
458319,chrY,90833633,+,2,0,56,0.035714,0.000,TACAG,0,1.0,2,0,56,0.035714,0.000000,TACAG,0,1.0
458320,chrY,90833648,+,1,0,55,0.018182,0.000,CTCAA,0,1.0,1,0,55,0.018182,0.000000,CTCAA,0,1.0

In [10]:
# create ensemble predictions for Ko after correction
ko_ensemble_corrected = pd.merge(ko_iforest_dfCTaggr.query("y_hat == 1"), 
                                 ko_cnn_dfCTaggr.query("y_hat == 1"),
                                 how="inner", on=["region", "position", "strand"])
ko_ensemble_corrected

,region,position,strand,T_native_x,T_corrected_x,depth_stranded_x,Tfreq_native_x,Tfreq_corrected_x,5mer_x,y_hat_x,p_value_x,T_native_y,T_corrected_y,depth_stranded_y,Tfreq_native_y,Tfreq_corrected_y,5mer_y,y_hat_y,p_value_y
0,chr1,4855906,-,70,33,70,1.000000,0.471429,CGCGG,1,1.000000,57,14,70,0.814286,0.200000,CGCGG,1,1.000000
1,chr1,4911240,+,12,4,75,0.160000,0.053333,CCCTT,1,1.000000,12,1,75,0.160000,0.013333,CCCTT,1,1.000000
2,chr1,4916086,+,9,4,95,0.094737,0.042105,ACCGA,1,1.000000,8,3,95,0.084211,0.031579,ACCGA,1,1.000000
3,chr1,4916336,+,25,7,104,0.240385,0.067308,GCCGA,1,0.000316,24,20,104,0.230769,0.192308,GCCGA,1,0.000316
4,chr1,4962288,+,5,3,101,0.049505,0.029703,AGCAG,1,1.000000,5,2,101,0.049505,0.019802,AGCAG,1,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4642,chrY,90795578,+,3,2,67,0.044776,0.029851,CTCCC,1,1.000000,3,1,67,0.044776,0.014925,CTCCC,1,1.000000
4643,chrY,90797052,+,9,2,87,0.103448,0.022989,CCCGC,1,1.000000,9,2,87,0.103448,0.022989,CCCGC,1,1.000000
4644,chrY,90797171,+,9,2,71,0.126761,0.028169,TTCAC,1,1.000000,9,1,71,0.126761,0.014085,TTCAC,1,1.000000
4645,chrY,90827645,+,39,30,59,0.661017,0.508475,GACGG,1,1.000000,32,4,59,0.542373,0.067797,GACGG,1,1.000000
4646,chrY,90833582,+,38,30,56,0.678571,0.535714,GACGG,1,1.000000,32,3,56,0.571429,0.053571,GACGG,1,1.000000